# Generated by Django 5.2.17 on 2026-10-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leg",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Ida / único"), (2, "Volta")],
                        null=True,
                        verbose_name="jogo do confronto",
                    ),
                ),
                (
                    "kickoff_at",
                    models.DateTimeField(db_index=True, verbose_name="início (UTC)"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="fim (UTC)"
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="estádio"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="cidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendado"),
                            ("live", "Ao vivo"),
                            ("finished", "Encerrado"),
                            ("postponed", "Adiado"),
                            ("suspended", "Suspenso"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="scheduled",
                        editable=False,
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_half", "1º tempo"),
                            ("half_time", "Intervalo"),
                            ("second_half", "2º tempo"),
                            ("extra_time", "Prorrogação"),
                            ("penalties", "Pênaltis"),
                        ],
                        editable=False,
                        max_length=12,
                        null=True,
                        verbose_name="período",
                    ),
                ),
                (
                    "period_started_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="início do período",
                    ),
                ),
                (
                    "home_score",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="gols mandante"
                    ),
                ),
                (
                    "away_score",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="gols visitante"
                    ),
                ),
                (
                    "home_penalties",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="pênaltis mandante",
                    ),
                ),
                (
                    "away_penalties",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="pênaltis visitante",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="versão"
                    ),
                ),
                (
                    "attendance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="público pagante"
                    ),
                ),
                (
                    "revenue_cents",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="renda (centavos)"
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="competitions.team",
                        verbose_name="visitante",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="competitions.group",
                        verbose_name="grupo",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="competitions.team",
                        verbose_name="mandante",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="competitions.round",
                        verbose_name="rodada",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida",
                "verbose_name_plural": "partidas",
                "db_table": "matches",
                "ordering": ["kickoff_at", "id"],
                "permissions": [
                    ("post_event", "Pode lançar eventos de partida"),
                    ("void_event", "Pode cancelar lançamentos"),
                    ("change_status", "Pode mudar o status da partida"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nome")),
                ("url", models.URLField(blank=True, verbose_name="link")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("open_tv", "TV aberta"),
                            ("pay_tv", "TV fechada"),
                            ("streaming", "Streaming"),
                            ("radio", "Rádio"),
                        ],
                        default="streaming",
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="matches.match",
                        verbose_name="partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "transmissão",
                "verbose_name_plural": "transmissões",
                "db_table": "match_broadcasts",
                "ordering": ["match", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MatchLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formation",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 4-3-3",
                        max_length=12,
                        verbose_name="esquema",
                    ),
                ),
                (
                    "coach",
                    models.CharField(blank=True, max_length=80, verbose_name="técnico"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="matches.match",
                        verbose_name="partida",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "escalação",
                "verbose_name_plural": "escalações",
                "db_table": "match_lineups",
            },
        ),
        migrations.CreateModel(
            name="MatchLineupPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=80, verbose_name="nome"),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="número"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Goleiro"),
                            ("DF", "Defensor"),
                            ("MF", "Meio-campista"),
                            ("FW", "Atacante"),
                        ],
                        max_length=2,
                        verbose_name="posição",
                    ),
                ),
                ("starter", models.BooleanField(default=True, verbose_name="titular")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="matches.matchlineup",
                        verbose_name="escalação",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.player",
                        verbose_name="jogador",
                    ),
                ),
            ],
            options={
                "verbose_name": "jogador escalado",
                "verbose_name_plural": "jogadores escalados",
                "db_table": "match_lineup_players",
                "ordering": ["lineup", "-starter", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MatchOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("referee", "Árbitro"),
                            ("assistant", "Assistente"),
                            ("fourth", "Quarto árbitro"),
                            ("var", "VAR"),
                            ("avar", "Assistente de VAR"),
                        ],
                        max_length=12,
                        verbose_name="função",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="UF"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="matches.match",
                        verbose_name="partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "arbitragem",
                "verbose_name_plural": "arbitragem",
                "db_table": "match_officials",
                "ordering": ["match", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MatchStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("possession", "Posse de bola (%)"),
                            ("shots", "Finalizações"),
                            ("shots_on_target", "Finalizações no gol"),
                            ("corners", "Escanteios"),
                            ("fouls", "Faltas"),
                            ("offsides", "Impedimentos"),
                            ("saves", "Defesas"),
                            ("passes", "Passes"),
                        ],
                        max_length=20,
                        verbose_name="estatística",
                    ),
                ),
                ("value", models.PositiveIntegerField(verbose_name="valor")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="matches.match",
                        verbose_name="partida",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "estatística",
                "verbose_name_plural": "estatísticas",
                "db_table": "match_stats",
                "ordering": ["match", "key", "team"],
            },
        ),
        migrations.CreateModel(
            name="Tie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ordem"),
                ),
                (
                    "legs",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Jogo único"), (2, "Ida e volta")],
                        verbose_name="jogos",
                    ),
                ),
                (
                    "extra_time",
                    models.BooleanField(
                        choices=[(True, "Sim"), (False, "Não")],
                        verbose_name="tem prorrogação",
                    ),
                ),
                (
                    "decided_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aggregate", "No agregado"),
                            ("extra_time", "Na prorrogação"),
                            ("penalties", "Nos pênaltis"),
                        ],
                        max_length=12,
                        verbose_name="decidido",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ties",
                        to="competitions.round",
                        verbose_name="rodada",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ties",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
                (
                    "team_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time A",
                    ),
                ),
                (
                    "team_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time B",
                    ),
                ),
                (
                    "winner_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="vencedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "confronto",
                "verbose_name_plural": "confrontos",
                "db_table": "ties",
                "ordering": ["stage", "round__number", "position"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="tie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="matches.tie",
                verbose_name="confronto",
            ),
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="sequência")),
                ("type", models.CharField(max_length=24, verbose_name="tipo")),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="período"
                    ),
                ),
                (
                    "minute",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="minuto"
                    ),
                ),
                (
                    "stoppage",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="acréscimo"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="dados"),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelado em"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=80, verbose_name="chave de idempotência"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("operator", "Tela do operador"),
                            ("admin", "Django Admin"),
                            ("system", "Sistema"),
                            ("feed", "Feed de provedor"),
                            ("script", "Script"),
                        ],
                        default="operator",
                        max_length=12,
                        verbose_name="origem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, verbose_name="lançado em"),
                ),
                (
                    "annuls_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annulments",
                        to="matches.matchevent",
                        verbose_name="anula o evento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lançado por",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="matches.match",
                        verbose_name="partida",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.player",
                        verbose_name="jogador",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cancelado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "db_table": "match_events",
                "ordering": ["match", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["type", "created_at"], name="event_type_created"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "sequence"), name="uniq_event_sequence"
                    ),
                    models.UniqueConstraint(
                        fields=("match", "idempotency_key"),
                        name="uniq_event_idempotency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("voided_at__isnull", True), ("voided_by__isnull", True)
                            ),
                            models.Q(
                                ("voided_at__isnull", False),
                                ("voided_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="event_void_has_author",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="matchlineup",
            constraint=models.UniqueConstraint(
                fields=("match", "team"), name="uniq_lineup_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchstat",
            constraint=models.UniqueConstraint(
                fields=("match", "team", "key"), name="uniq_match_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="tie",
            constraint=models.CheckConstraint(
                condition=models.Q(("legs__in", [1, 2])), name="tie_legs_1_or_2"
            ),
        ),
        migrations.AddConstraint(
            model_name="tie",
            constraint=models.CheckConstraint(
                condition=models.Q(("team_a", models.F("team_b")), _negated=True),
                name="tie_distinct_teams",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["stage", "round"], name="match_stage_round"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="match_status"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["finished_at"], name="match_finished_at"),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tie__isnull", True), ("group__isnull", True), _connector="OR"
                ),
                name="match_tie_xor_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="match_distinct_teams",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period__isnull", True),
                    ("status__in", ["live", "suspended"]),
                    _connector="OR",
                ),
                name="match_period_only_live_or_suspended",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("leg__isnull", True), ("tie__isnull", True)),
                    models.Q(("leg__in", [1, 2]), ("tie__isnull", False)),
                    _connector="OR",
                ),
                name="match_leg_with_tie",
            ),
        ),
    ]
