# Generated by Django 5.2.17 on 2026-10-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_remove_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Agendado"),
                    ("delayed", "Atrasado"),
                    ("live", "Ao vivo"),
                    ("finished", "Encerrado"),
                    ("postponed", "Adiado"),
                    ("suspended", "Suspenso"),
                    ("cancelled", "Cancelado"),
                ],
                default="scheduled",
                editable=False,
                max_length=12,
                verbose_name="status",
            ),
        ),
    ]
