# Generated by Django 5.2.17 on 2026-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_match_status_delayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="clock_paused_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="relógio parado desde",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="partial_info",
            field=models.BooleanField(
                default=False,
                help_text='Marque quando o jogo tem só informações parciais: o site mostra "Informações parciais" no lugar de "Ao vivo" e não mostra o tempo de jogo.',
                verbose_name="informações parciais",
            ),
        ),
    ]
