# Generated by Django 5.2.17 on 2026-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_match_partial_info_clock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchlineupplayer",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GK", "Goleiro"),
                    ("LAD", "Lateral-direito"),
                    ("DF", "Zagueiro"),
                    ("LAE", "Lateral-esquerdo"),
                    ("VOL", "Volante"),
                    ("MF", "Meio-campista"),
                    ("FW", "Atacante"),
                ],
                max_length=3,
                verbose_name="posição",
            ),
        ),
    ]
