# Generated by Django 5.2.17 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0006_lineup_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_half", "1º tempo"),
                    ("half_time", "Intervalo"),
                    ("second_half", "2º tempo"),
                    ("extra_time", "1º tempo da prorrogação"),
                    ("extra_half_time", "Intervalo da prorrogação"),
                    ("extra_second_half", "2º tempo da prorrogação"),
                    ("penalties", "Pênaltis"),
                ],
                editable=False,
                max_length=20,
                null=True,
                verbose_name="período",
            ),
        ),
        migrations.AlterField(
            model_name="matchevent",
            name="period",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="período"
            ),
        ),
    ]
