# Generated by Django 5.2.17 on 2026-10-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Oficial (só encerrados)"),
                            ("live", "Ao vivo"),
                        ],
                        max_length=8,
                        verbose_name="tabela",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="posição")),
                (
                    "played",
                    models.PositiveSmallIntegerField(default=0, verbose_name="J"),
                ),
                ("won", models.PositiveSmallIntegerField(default=0, verbose_name="V")),
                (
                    "drawn",
                    models.PositiveSmallIntegerField(default=0, verbose_name="E"),
                ),
                ("lost", models.PositiveSmallIntegerField(default=0, verbose_name="D")),
                (
                    "goals_for",
                    models.PositiveSmallIntegerField(default=0, verbose_name="GP"),
                ),
                (
                    "goals_against",
                    models.PositiveSmallIntegerField(default=0, verbose_name="GC"),
                ),
                ("points", models.SmallIntegerField(default=0, verbose_name="Pts")),
                (
                    "yellow_cards",
                    models.PositiveSmallIntegerField(default=0, verbose_name="CA"),
                ),
                (
                    "red_cards",
                    models.PositiveSmallIntegerField(default=0, verbose_name="CV"),
                ),
                (
                    "tied",
                    models.BooleanField(
                        default=False, verbose_name="empate não desfeito"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="competitions.group",
                        verbose_name="grupo",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "linha da classificação",
                "verbose_name_plural": "classificação",
                "db_table": "standings",
                "ordering": ["group", "kind", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "kind", "team"), name="uniq_standing_team"
                    )
                ],
            },
        ),
    ]
