# Generated by Django 5.2.17 on 2026-10-04 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_delete_player"),
        ("standings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standing",
            name="adjustment",
            field=models.SmallIntegerField(default=0, verbose_name="ajuste de pontos"),
        ),
        migrations.CreateModel(
            name="PointAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.SmallIntegerField(
                        help_text="Negativo tira pontos (punição); positivo dá pontos. Não pode ser 0.",
                        verbose_name="pontos",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Aparece na legenda da classificação, ex.: escalação irregular.",
                        max_length=200,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="cadastrada em"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_adjustments",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "punição ou bonificação",
                "verbose_name_plural": "punições e bonificações (pontos)",
                "db_table": "point_adjustments",
                "ordering": ["stage", "created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("points", 0), _negated=True),
                        name="point_adjustment_not_zero",
                    )
                ],
            },
        ),
    ]
