# Generated by Django 5.2.17 on 2026-10-04 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_temporada_cruzando_o_ano"),
        ("standings", "0002_point_adjustments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex.: Classificação geral, Vaga na Série D.",
                        max_length=80,
                        verbose_name="nome",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("overall", "Geral do torneio"),
                            ("custom", "Personalizada (times escolhidos)"),
                        ],
                        default="overall",
                        max_length=8,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "points_win",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="pontos por vitória"
                    ),
                ),
                (
                    "points_draw",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="pontos por empate"
                    ),
                ),
                (
                    "points_loss",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="pontos por derrota"
                    ),
                ),
                (
                    "show_on_competition",
                    models.BooleanField(
                        default=False,
                        help_text="Aparece como botão ao lado da classificação.",
                        verbose_name="mostrar na página da competição",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="competitions.season",
                        verbose_name="temporada",
                    ),
                ),
                (
                    "show_on_stages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Botão ao lado da classificação quando a página mostra uma destas fases.",
                        related_name="rankings_shown",
                        to="competitions.stage",
                        verbose_name="mostrar na página destas fases",
                    ),
                ),
                (
                    "stages",
                    models.ManyToManyField(
                        help_text="Os jogos destas fases somam (todos, mata-mata inclusive). Deixe de fora as que não contam.",
                        related_name="rankings_included",
                        to="competitions.stage",
                        verbose_name="fases que entram",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Só na personalizada: os times que disputam (os demais não aparecem).",
                        related_name="rankings",
                        to="competitions.team",
                        verbose_name="times",
                    ),
                ),
            ],
            options={
                "verbose_name": "classificação geral ou personalizada",
                "verbose_name_plural": "classificações gerais e personalizadas",
                "db_table": "rankings",
                "ordering": ["season", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="RankingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nome")),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use o formato #RRGGBB."
                            )
                        ],
                        verbose_name="cor",
                    ),
                ),
                (
                    "position_from",
                    models.PositiveSmallIntegerField(verbose_name="da posição"),
                ),
                (
                    "position_to",
                    models.PositiveSmallIntegerField(verbose_name="até a posição"),
                ),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="standings.ranking",
                        verbose_name="classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "zona",
                "verbose_name_plural": "zonas (faixas coloridas)",
                "db_table": "ranking_zones",
                "ordering": ["ranking", "position_from"],
            },
        ),
        migrations.CreateModel(
            name="RankingCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="ordem")),
                ("key", models.CharField(max_length=32, verbose_name="critério")),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="standings.ranking",
                        verbose_name="classificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério de desempate",
                "verbose_name_plural": "critérios de desempate (na ordem)",
                "db_table": "ranking_criteria",
                "ordering": ["ranking", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ranking", "position"),
                        name="uniq_ranking_criterion_position",
                    )
                ],
            },
        ),
    ]
