# Generated by Django 5.2.17 on 2026-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standings", "0003_classificacoes_gerais_e_personalizadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="ranking",
            name="group_position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Só em “posição nos grupos”: compara quem está nesta posição em cada grupo da fase (ex.: 3).",
                null=True,
                verbose_name="posição no grupo",
            ),
        ),
        migrations.AddField(
            model_name="ranking",
            name="skip_extra_teams",
            field=models.BooleanField(
                default=False,
                help_text="Grupos de tamanhos diferentes: nos maiores, os jogos contra quem passa do tamanho do menor grupo (ex.: o 5º num grupo de 5, se o menor tem 4) não contam na comparação.",
                verbose_name="desconsiderar jogos contra os últimos dos grupos maiores",
            ),
        ),
        migrations.AlterField(
            model_name="ranking",
            name="scope",
            field=models.CharField(
                choices=[
                    ("overall", "Geral do torneio"),
                    ("custom", "Personalizada (times escolhidos)"),
                    ("position", "Posição nos grupos (ex.: melhores terceiros)"),
                ],
                default="overall",
                max_length=8,
                verbose_name="tipo",
            ),
        ),
    ]
