# Generated by Django 5.2.17 on 2026-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "prefix",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="prefixo",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False, max_length=64, unique=True, verbose_name="hash"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=60, verbose_name="limite por minuto"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="último uso"
                    ),
                ),
            ],
            options={
                "verbose_name": "chave da API pública",
                "verbose_name_plural": "chaves da API pública",
                "db_table": "api_keys",
                "ordering": ["name"],
            },
        ),
    ]
