# Generated by Django 5.2.17 on 2026-10-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="usuário"
                    ),
                ),
                (
                    "action",
                    models.CharField(db_index=True, max_length=40, verbose_name="ação"),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=60, verbose_name="objeto"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="id do objeto"
                    ),
                ),
                (
                    "match_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="partida"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="dados"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="requisição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="quando"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "auditoria",
                "db_table": "audit_log",
                "ordering": ["-created_at", "-id"],
                "permissions": [("view_metrics", "Pode ver as métricas")],
            },
        ),
    ]
