# Generated by Django 5.2.17 on 2026-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("match", "Partida"),
                            ("standings", "Classificação"),
                            ("goals", "Últimos gols"),
                        ],
                        max_length=16,
                        verbose_name="tópico",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="mensagem")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="criada em"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicada em"
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem do outbox",
                "verbose_name_plural": "outbox",
                "db_table": "outbox",
                "ordering": ["id"],
            },
        ),
    ]
