# Generated by Django 5.2.17 on 2026-10-03 16:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="slug"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="ordem"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="nome curto"
                    ),
                ),
            ],
            options={
                "verbose_name": "competição",
                "verbose_name_plural": "competições",
                "db_table": "competitions",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "short_name",
                    models.CharField(
                        help_text="Até 4 letras, ex.: SPT",
                        max_length=4,
                        verbose_name="sigla",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="cidade"),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="#12306B",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use o formato #RRGGBB."
                            )
                        ],
                        verbose_name="cor principal",
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        default="#FFFFFF",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use o formato #RRGGBB."
                            )
                        ],
                        verbose_name="cor secundária",
                    ),
                ),
                ("crest_url", models.URLField(blank=True, verbose_name="escudo (URL)")),
            ],
            options={
                "verbose_name": "time",
                "verbose_name_plural": "times",
                "db_table": "teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="ano")),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="competitions.competition",
                        verbose_name="competição",
                    ),
                ),
            ],
            options={
                "verbose_name": "temporada",
                "verbose_name_plural": "temporadas",
                "db_table": "seasons",
                "ordering": ["competition__position", "-year"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("league", "Pontos corridos"),
                            ("groups", "Grupos"),
                            ("knockout", "Mata-mata"),
                        ],
                        max_length=12,
                        verbose_name="formato",
                    ),
                ),
                (
                    "points_win",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="pontos por vitória"
                    ),
                ),
                (
                    "points_draw",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="pontos por empate"
                    ),
                ),
                (
                    "points_loss",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="pontos por derrota"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="competitions.season",
                        verbose_name="temporada",
                    ),
                ),
            ],
            options={
                "verbose_name": "fase",
                "verbose_name_plural": "fases",
                "db_table": "stages",
                "ordering": ["season", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="número")),
                (
                    "name",
                    models.CharField(blank=True, max_length=60, verbose_name="nome"),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "rodada",
                "verbose_name_plural": "rodadas",
                "db_table": "rounds",
                "ordering": ["stage", "number"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="nome")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
                "db_table": "groups",
                "ordering": ["stage", "name"],
            },
        ),
        migrations.CreateModel(
            name="StageCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="ordem")),
                ("key", models.CharField(max_length=32, verbose_name="critério")),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério de desempate",
                "verbose_name_plural": "critérios de desempate",
                "db_table": "stage_criteria",
                "ordering": ["stage", "position"],
            },
        ),
        migrations.CreateModel(
            name="StandingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nome")),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Use o formato #RRGGBB."
                            )
                        ],
                        verbose_name="cor",
                    ),
                ),
                (
                    "position_from",
                    models.PositiveSmallIntegerField(verbose_name="da posição"),
                ),
                (
                    "position_to",
                    models.PositiveSmallIntegerField(verbose_name="até a posição"),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="competitions.stage",
                        verbose_name="fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "zona da legenda",
                "verbose_name_plural": "zonas da legenda",
                "db_table": "standing_zones",
                "ordering": ["stage", "position_from"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="número"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Goleiro"),
                            ("DF", "Defensor"),
                            ("MF", "Meio-campista"),
                            ("FW", "Atacante"),
                        ],
                        max_length=2,
                        verbose_name="posição",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "jogador",
                "verbose_name_plural": "jogadores",
                "db_table": "players",
                "ordering": ["team", "number", "name"],
            },
        ),
        migrations.CreateModel(
            name="GroupTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_order",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ordem do sorteio"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_teams",
                        to="competitions.group",
                        verbose_name="grupo",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_entries",
                        to="competitions.team",
                        verbose_name="time",
                    ),
                ),
            ],
            options={
                "verbose_name": "time do grupo",
                "verbose_name_plural": "times do grupo",
                "db_table": "group_teams",
                "ordering": ["group", "team__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("competition", "year"), name="uniq_season_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("stage", "number"), name="uniq_round_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("stage", "name"), name="uniq_group_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagecriterion",
            constraint=models.UniqueConstraint(
                fields=("stage", "position"), name="uniq_stage_criterion_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagecriterion",
            constraint=models.UniqueConstraint(
                fields=("stage", "key"), name="uniq_stage_criterion_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="standingzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_from__lte", models.F("position_to"))),
                name="zone_range_ok",
            ),
        ),
        migrations.AddConstraint(
            model_name="standingzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__regex", "^#[0-9A-Fa-f]{6}$")),
                name="zone_color_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="standingzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_from__gte", 1)), name="zone_from_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupteam",
            constraint=models.UniqueConstraint(
                fields=("group", "team"), name="uniq_group_team"
            ),
        ),
    ]
