# Generated by Django 5.2.17 on 2026-10-04 05:16

import competitions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_delete_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="crest_file",
            field=models.FileField(
                blank=True,
                help_text="PNG, JPG ou WebP, até 512 KB. Se enviado, vale no lugar da URL.",
                upload_to="escudos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "webp"]
                    ),
                    competitions.models.validate_crest_size,
                ],
                verbose_name="escudo (arquivo)",
            ),
        ),
    ]
