# Generated by Django 5.2.17 on 2026-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_team_crest_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="end_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Só para temporada que cruza o ano, como as europeias: 2027 em 2026/2027. Vazio = ano único.",
                null=True,
                verbose_name="ano final",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.PositiveSmallIntegerField(
                help_text="Ano de início (ex.: 2026).", verbose_name="ano"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_year__isnull", True),
                    ("end_year__gt", models.F("year")),
                    _connector="OR",
                ),
                name="season_end_after_start",
                violation_error_message="O ano final vem depois do ano de início (ex.: 2026/2027).",
            ),
        ),
    ]
