# Generated by Django 5.2.17 on 2026-10-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_temporada_cruzando_o_ano"),
        ("standings", "0004_ranking_group_position_ranking_skip_extra_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standingzone",
            name="ranking",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: ex. “Melhores terceiros”. Quem estiver fora da faixa abaixo fica sem a cor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conditional_zones",
                to="standings.ranking",
                verbose_name="só se estiver na classificação",
            ),
        ),
        migrations.AddField(
            model_name="standingzone",
            name="ranking_position_from",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nela, da posição"
            ),
        ),
        migrations.AddField(
            model_name="standingzone",
            name="ranking_position_to",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="nela, até a posição"
            ),
        ),
    ]
